#!/bin/bash
#
# git branch-from commit-reference new-branch
#
# create a new branch and reset current branch to the commit-reference
#

set -e

if [ -z $1 ]
then
    echo "Usage: git branch-from <commit-reference> <new-branch>";
    exit 1;
else
    STARTPOINT=`git rev-parse $1`
fi
if [ -z $2 ]
then
    echo "Usage: git branch-from <commit-reference> <new-branch>";
    exit 1;
else
    BRANCH=$2
fi

CURRENT_BRANCH=`git branch | grep '*' | perl -e '<STDIN> =~ /^..(.+)$/;print $1'`

# If the branch already exists, we have to merge it with the current branch
if ! [ -z `git branch -a | grep $BRANCH` ]
then
    echo "$BRANCH already exists. Please specify a new branch name."
    exit 1;
fi

echo "Creating $BRANCH"
git branch $BRANCH
echo "Resetting $CURRENT_BRANCH to $STARTPOINT"
git reset --hard $STARTPOINT
echo "Switching to branch $BRANCH"
git checkout $BRANCH
